CREATE  TABLE `bigdata`.`twitter_user_id_mapping` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `TWITTER_API_ID` INT NOT NULL ,
  `TWITTER_SCREENNAME` VARCHAR(45) NOT NULL ,
  `TWITTER_SEARCH_ID` INT NULL ,
  PRIMARY KEY (`id`) );
